#!/usr/bin/env sh

# DESCRIPTION
#

# Glorified Echo, this just prevents the headache of having to reset the color all the time
print () { 
    echo -e "$1 ${RESET_COLOR}" 
}

# print for critical security errors, these are things that need to be fixed
printCritical () { 
    echo -e "${RED}[x][CRITICAL]${RESET_COLOR} $1 ${RESET_COLOR}" 
}

# print for basic warning, these are things that should be fixed
printWarning () { 
    echo -e "${YELLOW}[*][WARNING]${RESET_COLOR} $1 ${RESET_COLOR}" 
}

# print for saying things are okay
printSecure () { 
    echo -e "${GREEN}[✓][SECURE]${RESET_COLOR} $1 ${RESET_COLOR}" 
}